"""
The self-diagnosing home: a rigorous (deliberately un-hyped) prognostics simulation.

Thesis under test: the telemetry a home already collects for *convenience* can be repurposed
to predict *equipment* failure and hand a technician a pre-arrival diagnostic — reusing the
sensor, but pointing it at the machine instead of the occupant.

This file does not argue the thesis; it stress-tests it. Every claim is earned against an
adversarial design (informed by a DeepSeek review):

  1. Load drives *wear itself*, not just the observation. Summer accelerates real degradation
     and biases the raw signal — the two are entangled, as in reality.
  2. Calibration is judged on a right-CENSORED, heterogeneous fleet where most units never
     fail in the observation window — via a PIT histogram. This is the linchpin: if the 80%
     RUL interval does not cover ~80% of true failures, the value proposition collapses.
  3. The naive baseline is a fair one — CUSUM on the observed signal — not a straw threshold.
  4. A reject-option: when the wear signature is unobservable, the estimator must say
     "I don't know," not emit a confidently wrong number.
  5. A model-MISSPECIFICATION test: truth is generated by a load-dependent Ornstein-Uhlenbeck
     process; we fit the (wrong) Wiener model anyway and report the miscalibration honestly.
  6. The hype is quantified, not hidden: minimum detectable wear vs. sensor SNR, i.e. the gap
     between a $500 vibration sensor and what a thermostat/plug can actually see.

Author's model choices are simple on purpose — legible physics an estate engineer can argue
with — but the *evaluation* is strict.
"""
from __future__ import annotations

import numpy as np
from dataclasses import dataclass, field
from scipy.stats import invgauss

RNG = np.random.default_rng(20260705)
DT = 1.0                     # one step = one day
HORIZON_DAYS = 540           # ~18 months of observation
YEAR = 365.0


# ---------------------------------------------------------------------------- load model
def seasonal_load(t: np.ndarray, phase: float = 0.0) -> np.ndarray:
    """Normalized HVAC thermal load in [~0,1]: a hot-summer peak plus a smaller winter-heat
    shoulder and diurnal-averaged noise. This same curve both (a) accelerates wear and
    (b) biases the observed power — the entanglement DeepSeek insisted on."""
    summer = np.exp(-0.5 * ((np.sin(np.pi * (t / YEAR + phase)))**2 - 1.0)**2 / 0.10)
    winter = 0.45 * np.exp(-0.5 * ((np.cos(np.pi * (t / YEAR + phase)))**2 - 1.0)**2 / 0.10)
    base = 0.25 + 0.75 * np.clip(summer + winter, 0, 1)
    return np.clip(base + 0.03 * RNG.standard_normal(t.shape), 0.02, 1.2)


# ----------------------------------------------------------------- degradation processes
@dataclass
class Unit:
    """One asset. True latent degradation X accumulates; hard failure at first passage to D.
    `kind` selects the truth-generating dynamics (well-specified vs misspecified vs low-obs)."""
    kind: str
    mu0: float                       # baseline daily wear rate
    load_gain: float                 # how much load accelerates wear (μ = mu0*(1+load_gain*load))
    sigma: float                     # process (wear) volatility
    D: float = 1.0                   # failure threshold on X
    beta: float = 0.0                # load -> observation bias (confound), on OBSERVED signal
    tau: float = 0.02                # sensor noise std (SNR knob; the "what can a Nest see" dial)
    ou_theta: float = 0.0            # OU mean-reversion (misspecification); 0 => Wiener truth
    X: np.ndarray = field(default=None)
    t_fail: float = np.inf
    load: np.ndarray = field(default=None)

    def simulate(self, n: int) -> None:
        t = np.arange(n) * DT
        self.load = seasonal_load(t, phase=RNG.uniform(0, 2))
        x = np.zeros(n)
        for k in range(1, n):
            mu_k = self.mu0 * (1.0 + self.load_gain * self.load[k])
            drift = mu_k * DT
            if self.ou_theta > 0:
                drift += -self.ou_theta * (x[k-1] - mu_k * (k*DT)) * DT
            x[k] = x[k-1] + drift + self.sigma * np.sqrt(DT) * RNG.standard_normal()
            x[k] = max(x[k], x[k-1] - 3*self.sigma)
        self.X = x
        crossed = np.where(x >= self.D)[0]
        self.t_fail = crossed[0] * DT if crossed.size else np.inf

    def observe(self) -> np.ndarray:
        """Convenience telemetry: degradation + load bias + sensor noise. This is all the
        estimator ever sees — never the latent X, never t_fail."""
        n = len(self.X)
        return self.X + self.beta * self.load + self.tau * RNG.standard_normal(n)


# ------------------------------------------------------------- online estimator (Kalman)
class RULEstimator:
    """Kalman filter on state [X, mu] with a random-walk drift, plus a load-bias regressor.
    Produces an RUL predictive distribution by sampling the (X, mu) posterior and applying the
    Wiener first-passage (inverse-Gaussian) law to the remaining distance D - X.

    Crucially it carries a REJECT-OPTION: if the estimated wear rate is not significantly
    positive (mu small relative to its own posterior std), it returns rul=None ("I don't know")
    rather than a confident number — the honest answer for an unobservable / random failure."""

    def __init__(self, D: float, sigma_hat: float, tau: float, beta_known: float = 0.0,
                 q_mu: float = 3e-7):
        self.D = D
        self.tau = tau
        self.beta = beta_known
        self.sig = sigma_hat
        self.q_mu = q_mu
        self.m = np.array([0.0, 5e-4])
        self.P = np.diag([1e-3, 1e-5])

    def step(self, y: float, load: float) -> None:
        dt = DT
        F = np.array([[1.0, dt], [0.0, 1.0]])
        Q = np.array([[self.sig**2 * dt, 0.0], [0.0, self.q_mu]])
        self.m = F @ self.m
        self.P = F @ self.P @ F.T + Q
        H = np.array([[1.0, 0.0]])
        z = y - self.beta * load
        S = H @ self.P @ H.T + self.tau**2
        K = (self.P @ H.T) / S
        self.m = self.m + (K.flatten() * (z - (H @ self.m)[0]))
        self.P = (np.eye(2) - K @ H) @ self.P

    def _credible(self) -> bool:
        mu_m, mu_s = self.m[1], np.sqrt(max(self.P[1, 1], 1e-12))
        return mu_m / (mu_s + 1e-12) >= 1.0

    def rul_quantiles(self, qs=(0.10, 0.5, 0.90), n: int = 1500):
        if not self._credible():
            return None
        mu_m, mu_s = self.m[1], np.sqrt(max(self.P[1, 1], 1e-12))
        x_m, x_s = self.m[0], np.sqrt(max(self.P[0, 0], 1e-12))
        mu = np.clip(RNG.normal(mu_m, mu_s, n), 1e-9, None)
        x = RNG.normal(x_m, x_s, n)
        dist = np.clip(self.D - x, 1e-6, None)
        mean = dist / mu
        shape = (dist / self.sig)**2
        rul = np.clip(invgauss.rvs(mu=mean / shape, scale=shape, size=n, random_state=RNG),
                      0, 5 * YEAR)
        return np.quantile(rul, qs)

    def rul_cdf_at(self, t_query: float, n: int = 4000) -> float | None:
        if not self._credible():
            return None
        mu_m, mu_s = self.m[1], np.sqrt(max(self.P[1, 1], 1e-12))
        x_m, x_s = self.m[0], np.sqrt(max(self.P[0, 0], 1e-12))
        mu = np.clip(RNG.normal(mu_m, mu_s, n), 1e-9, None)
        x = RNG.normal(x_m, x_s, n)
        dist = np.clip(self.D - x, 1e-6, None)
        mean = dist / mu
        shape = (dist / self.sig)**2
        rul = invgauss.rvs(mu=mean / shape, scale=shape, size=n, random_state=RNG)
        return float(np.mean(rul <= t_query))

    def eta_point(self) -> float | None:
        if not self._credible():
            return None
        dist = max(self.D - self.m[0], 1e-6)
        return dist / max(self.m[1], 1e-9)


def cusum_alarm(y: np.ndarray, k: float, h: float) -> int | None:
    """Fair naive baseline: one-sided CUSUM on the observed signal. Returns first alarm index
    or None. (What a maintenance crew would actually implement without a state-space model.)"""
    s = 0.0
    ref = np.median(y[:60])
    for i in range(len(y)):
        s = max(0.0, s + (y[i] - ref - k))
        if s > h:
            return i
    return None


# --------------------------------------------------------------------- fleet populations
def make_unit(kind: str, tau: float) -> Unit:
    if kind == "compressor":
        return Unit(kind, mu0=RNG.uniform(0.0011, 0.0019), load_gain=RNG.uniform(0.8, 1.6),
                    sigma=RNG.uniform(0.010, 0.016), beta=0.06, tau=tau)
    if kind == "misspecified":
        return Unit(kind, mu0=RNG.uniform(0.0011, 0.0019), load_gain=RNG.uniform(0.8, 1.6),
                    sigma=RNG.uniform(0.012, 0.018), beta=0.06, tau=tau, ou_theta=0.004)
    if kind == "lowobs":
        return Unit(kind, mu0=RNG.uniform(0.0011, 0.0019), load_gain=RNG.uniform(0.8, 1.6),
                    sigma=RNG.uniform(0.010, 0.016), beta=0.55, tau=max(tau, 0.10))
    if kind == "healthy":
        return Unit(kind, mu0=1e-5, load_gain=0.0, sigma=0.010, beta=0.06, tau=tau)
    raise ValueError(kind)


def run_unit(u: Unit, load_aware: bool, record: bool = False) -> dict:
    """Stream the observed signal through the estimator. `record=True` stores the full RUL
    band each step (for the exemplar figure); otherwise only a cheap ETA scan drives the
    alarm, keeping fleet studies fast. Alarm = credible ETA within a 30-day window, confirmed
    by a sampled 90th-percentile RUL also inside it (interval-inside, not just point)."""
    y = u.observe()
    beta_known = u.beta if load_aware else 0.0
    est = RULEstimator(D=u.D, sigma_hat=0.013, tau=u.tau, beta_known=beta_known)
    rul_med, rul_lo, rul_hi = [], [], []
    alarm_t = None
    for k in range(len(y)):
        est.step(y[k], u.load[k])
        if record:
            q = est.rul_quantiles()
            if q is None:
                rul_lo.append(np.nan); rul_med.append(np.nan); rul_hi.append(np.nan)
            else:
                rul_lo.append(q[0]); rul_med.append(q[1]); rul_hi.append(q[2])
        if alarm_t is None and k > 45:
            eta = est.eta_point()
            if eta is not None and eta <= 30:
                q = est.rul_quantiles(qs=(0.90,))
                if q is not None and q[0] <= 30:
                    alarm_t = k
    return {"y": y, "rul_med": np.array(rul_med), "rul_lo": np.array(rul_lo),
            "rul_hi": np.array(rul_hi), "alarm_t": alarm_t, "unit": u}


# ------------------------------------------------------------------------------- studies
def study_calibration(kind: str, n_units: int, load_aware: bool = True) -> dict:
    """Right-censored fleet PIT: at a fixed inspection day, for units that DO fail within the
    window, record the predictive CDF at the true RUL. If calibrated, these PIT values are
    Uniform(0,1) and nominal intervals achieve nominal coverage. Also record false-alarm rate
    on a healthy sub-fleet and the reject-rate (units the estimator declines to call)."""
    inspect_day = 200
    pit, covered80, lead_times, rejects, n_fail = [], 0, [], 0, 0
    for _ in range(n_units):
        u = make_unit(kind, tau=0.05)
        u.simulate(HORIZON_DAYS)
        res = run_unit(u, load_aware=load_aware)
        if res["alarm_t"] is not None and np.isfinite(u.t_fail):
            lead_times.append(u.t_fail - res["alarm_t"])
        if not np.isfinite(u.t_fail) or u.t_fail <= inspect_day:
            continue
        est = RULEstimator(D=u.D, sigma_hat=0.013, tau=u.tau,
                           beta_known=(u.beta if load_aware else 0.0))
        y = res["y"]
        for k in range(inspect_day):
            est.step(y[k], u.load[k])
        true_rul = u.t_fail - inspect_day
        p = est.rul_cdf_at(true_rul)
        if p is None:
            rejects += 1
            continue
        n_fail += 1
        pit.append(p)
        q = est.rul_quantiles(qs=(0.10, 0.90))
        covered80 += int(q[0] <= true_rul <= q[1])
    healthy_fa = fleet_false_alarm(n_units=max(200, n_units // 3), load_aware=load_aware)
    return {"pit": np.array(pit), "coverage80": covered80 / max(n_fail, 1),
            "lead_times": np.array(lead_times), "reject_rate": rejects / max(rejects + n_fail, 1),
            "n_calibratable": n_fail, "healthy_false_alarm": healthy_fa}


def fleet_false_alarm(n_units: int, load_aware: bool) -> float:
    fa = 0
    for _ in range(n_units):
        u = make_unit("healthy", tau=0.05)
        u.simulate(HORIZON_DAYS)
        res = run_unit(u, load_aware=load_aware)
        fa += int(res["alarm_t"] is not None)
    return fa / n_units


def study_observability(taus: np.ndarray, n_units: int = 120) -> dict:
    """Quantify the hype boundary: as sensor noise tau rises (a $500 vibration sensor -> a
    thermostat/plug), how does useful prognosis decay? Separate three outcomes."""
    useful, medlead, reject, fa = [], [], [], []
    for tau in taus:
        d = 0; nf = 0; rej = 0; leads = []
        for _ in range(n_units):
            u = make_unit("compressor", tau=tau)
            u.simulate(HORIZON_DAYS)
            if not np.isfinite(u.t_fail):
                continue
            nf += 1
            res = run_unit(u, load_aware=True)
            est = RULEstimator(D=u.D, sigma_hat=0.013, tau=tau, beta_known=u.beta)
            credible_ever = False
            for k in range(int(min(u.t_fail, HORIZON_DAYS))):
                est.step(res["y"][k], u.load[k])
                if est._credible():
                    credible_ever = True
                    break
            if not credible_ever:
                rej += 1
            if res["alarm_t"] is not None:
                lead = u.t_fail - res["alarm_t"]
                if lead >= 14:
                    d += 1; leads.append(lead)
        useful.append(d / max(nf, 1))
        reject.append(rej / max(nf, 1))
        medlead.append(float(np.median(leads)) if leads else 0.0)
        fa.append(fleet_false_alarm(n_units=60, load_aware=True))
    return {"tau": taus, "useful_lead": np.array(useful), "reject_frac": np.array(reject),
            "median_lead": np.array(medlead), "false_alarm": np.array(fa)}


if __name__ == "__main__":
    import json
    print("See the engine tier homeops/prognostics.py for the deployed, stdlib-only online")
    print("version. This script is the offline study (numpy/scipy) that calibrates it.")
    cal = study_calibration("compressor", n_units=300, load_aware=True)
    print(f"well-specified 80% coverage: {cal['coverage80']:.3f} from {cal['n_calibratable']} failures")
