"""Emit NATIVE Home Assistant automations for the life-safety subset.

The homeops Python layer is the AI-coordination + validation tier; it must not be the last line of
defense. This exports the life-safety blueprints (two-signal leak shutoff, freeze protection,
fire/CO response) as standard HA automation YAML that an installer drops into Home Assistant, where
they run **independently of the Python process** — surviving a homeops crash, restart, or upgrade.

    python -m homeops.exporters.homeassistant_export house_a house_b > life_safety.yaml

Entity ids are deployment-specific: pass `entity_maps={house_id: {role: ha_entity_id}}`; anything
unspecified falls back to a documented default so the output is always valid, editable YAML.
"""
from __future__ import annotations
import sys
import yaml

DEFAULTS = {
    "leak": "binary_sensor.leak_kitchen",
    "flow": "sensor.flow_meter",
    "valve": "valve.main_valve",
    "freeze": "sensor.freeze_garage",
    "thermostat": "climate.thermostat_main",
    "smoke_co": "binary_sensor.smoke_co_hall",
    "egress_light": "light.exterior_front",
    "egress_lock": "lock.egress_side",
    "hvac": "climate.hvac_main",
    "notify": "notify.notify",
}


def _resolver(entity_maps: dict | None, house_id: str):
    m = (entity_maps or {}).get(house_id, {})
    return lambda key: m.get(key, DEFAULTS[key])


def leak_automation(house_id: str, r, threshold: float = 30) -> dict:
    return {
        "id": f"homeops_leak_shutoff_{house_id}",
        "alias": f"homeops: leak two-signal shutoff ({house_id})",
        "mode": "single",
        "trigger": [{"platform": "state", "entity_id": r("leak"), "to": "on"}],
        "condition": [{"condition": "numeric_state", "entity_id": r("flow"), "above": threshold}],
        "action": [
            {"service": "valve.close_valve", "target": {"entity_id": r("valve")}},
            {"service": r("notify"), "data": {"message": f"{house_id}: leak confirmed (wet + abnormal flow) — main water shut off"}},
        ],
    }


def freeze_automation(house_id: str, r, freeze_f: float = 38, warm_f: int = 72) -> dict:
    return {
        "id": f"homeops_freeze_{house_id}",
        "alias": f"homeops: freeze protection ({house_id})",
        "mode": "single",
        "trigger": [{"platform": "numeric_state", "entity_id": r("freeze"), "below": freeze_f}],
        "action": [
            {"service": "climate.set_temperature", "target": {"entity_id": r("thermostat")}, "data": {"temperature": warm_f}},
            {"service": r("notify"), "data": {"message": f"{house_id}: freeze risk — heating vulnerable zone"}},
        ],
    }


def fire_co_automation(house_id: str, r) -> dict:
    return {
        "id": f"homeops_fire_co_{house_id}",
        "alias": f"homeops: fire/CO response ({house_id})",
        "mode": "single",
        "trigger": [{"platform": "state", "entity_id": r("smoke_co"), "to": "on"}],
        "action": [
            {"service": "light.turn_on", "target": {"entity_id": r("egress_light")}},
            {"service": "lock.unlock", "target": {"entity_id": r("egress_lock")}},   # designated egress only
            {"service": "climate.set_hvac_mode", "target": {"entity_id": r("hvac")}, "data": {"hvac_mode": "off"}},
            {"service": r("notify"), "data": {"message": f"{house_id}: FIRE/CO — egress unlocked, HVAC circulation stopped"}},
        ],
    }


def export_ha_automations(house_ids, entity_maps: dict | None = None,
                          threshold: float = 30, freeze_f: float = 38, warm_f: int = 72) -> str:
    autos = []
    for hid in house_ids:
        r = _resolver(entity_maps, hid)
        autos.append(leak_automation(hid, r, threshold))
        autos.append(freeze_automation(hid, r, freeze_f, warm_f))
        autos.append(fire_co_automation(hid, r))
    header = ("# NATIVE Home Assistant life-safety automations, generated by homeops.\n"
              "# These run inside Home Assistant independently of the homeops Python layer.\n"
              "# Life-safety alarms (smoke/CO/security monitoring) remain independent and primary;\n"
              "# these AUGMENT them. Review entity ids and test before relying on them.\n")
    return header + yaml.safe_dump(autos, sort_keys=False)


def write_ha_package(path: str, house_ids, entity_maps: dict | None = None) -> None:
    with open(path, "w") as f:
        f.write(export_ha_automations(house_ids, entity_maps))


if __name__ == "__main__":
    ids = sys.argv[1:] or ["house_a", "house_b"]
    print(export_ha_automations(ids))
